version: "3"
services:
  zeppelin:
    image: thrudhvangr/bda-zeppelin:0.11.0
    ports:
      - 8080:8080
    environment:
      ZEPPELIN_LOG_DIR: /logs
      ZEPPELIN_NOTEBOOK_DIR: /notebooks
    volumes:
      - "./logs:/logs"
      - "./notebooks:/notebooks"
      - "C:/4_MSE/Project_BDA_GroupeD/bda_group_d/data/open-data/data:/opt/zeppelin/data"


